version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: tiao_carreiro_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tiao_carreiro
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tiao_carreiro_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: tiao_carreiro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tiao_carreiro_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tiao_carreiro_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    environment:
      - APP_NAME=TiaoCarreiro
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=tiao_carreiro
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tiao_carreiro_network
    healthcheck:
      test: ["CMD", "php", "artisan", "migrate:status"]
      timeout: 20s
      retries: 10

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tiao_carreiro_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=laravel
      - PMA_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiao_carreiro_network

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: tiao_carreiro_portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - tiao_carreiro_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tiao_carreiro_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_APP_NAME=Top 5 Tião Carreiro & Pardinho
    depends_on:
      - backend
    networks:
      - tiao_carreiro_network
    stdin_open: true
    tty: true

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  portainer_data:
    driver: local

networks:
  tiao_carreiro_network:
    driver: bridge